import type { Sql } from "@/lib/db";

type SeedBrand = {
  name: string;
  name_en: string;
  aliases: string;
  weekend_off: boolean;
  category: string;
  note: string;
  weekend_votes: number;
  no_weekend_votes: number;
};

const SEED: SeedBrand[] = [
  {
    name: "可口可乐",
    name_en: "Coca-Cola",
    aliases: "CocaCola,Coke,可乐,Coca Cola",
    weekend_off: true,
    category: "食品饮料",
    note: "社区多记办公室岗位为双休，一线排班另算。",
    weekend_votes: 16,
    no_weekend_votes: 3,
  },
  {
    name: "百事",
    name_en: "Pepsi",
    aliases: "百事可乐,PepsiCo,百事可乐公司,乐事,Lay's,Lays",
    weekend_off: true,
    category: "食品饮料",
    note: "社区登记为双休，工厂排班因产线而异。",
    weekend_votes: 14,
    no_weekend_votes: 4,
  },
  {
    name: "雀巢",
    name_en: "Nestlé",
    aliases: "Nestle,雀巢咖啡,Nestle China",
    weekend_off: true,
    category: "食品饮料",
    note: "外企办公室多为双休。",
    weekend_votes: 15,
    no_weekend_votes: 2,
  },
  {
    name: "农夫山泉",
    name_en: "Nongfu Spring",
    aliases: "农夫,Nongfu,农夫山泉股份",
    weekend_off: false,
    category: "食品饮料",
    note: "社区反馈部分岗位加班和排班较满，因部门而异。",
    weekend_votes: 6,
    no_weekend_votes: 17,
  },
  {
    name: "怡宝",
    name_en: "C'estbon",
    aliases: "华润怡宝,Cestbon",
    weekend_off: false,
    category: "食品饮料",
    note: "社区登记为非双休，一线生产另论。",
    weekend_votes: 5,
    no_weekend_votes: 11,
  },
  {
    name: "娃哈哈",
    name_en: "Wahaha",
    aliases: "WAHAHA,杭州娃哈哈",
    weekend_off: false,
    category: "食品饮料",
    note: "社区反馈生产和部分岗位并非稳定双休。",
    weekend_votes: 4,
    no_weekend_votes: 13,
  },
  {
    name: "康师傅",
    name_en: "Master Kong",
    aliases: " Tingyi,康师傅方便面,康师傅饮品",
    weekend_off: false,
    category: "食品饮料",
    note: "社区登记一线与部分职能加班较多。",
    weekend_votes: 5,
    no_weekend_votes: 14,
  },
  {
    name: "统一",
    name_en: "Uni-President",
    aliases: "统一企业,统一方便面,统一冰红茶",
    weekend_off: false,
    category: "食品饮料",
    note: "社区登记为非双休，岗位差异大。",
    weekend_votes: 6,
    no_weekend_votes: 12,
  },
  {
    name: "伊利",
    name_en: "Yili",
    aliases: "伊利牛奶,内蒙古伊利,安慕希,金典",
    weekend_off: false,
    category: "食品饮料",
    note: "社区反馈产销岗位节奏紧，是否双休因岗而异。",
    weekend_votes: 7,
    no_weekend_votes: 16,
  },
  {
    name: "蒙牛",
    name_en: "Mengniu",
    aliases: "蒙牛乳业,特仑苏,纯甄",
    weekend_off: false,
    category: "食品饮料",
    note: "社区登记为非双休，办公室与一线不同。",
    weekend_votes: 6,
    no_weekend_votes: 15,
  },
  {
    name: "元气森林",
    name_en: "Genki Forest",
    aliases: "元気森林,外星人电解质水,GenkiForest",
    weekend_off: false,
    category: "食品饮料",
    note: "社区反馈互联网式节奏，双休不稳定。",
    weekend_votes: 4,
    no_weekend_votes: 18,
  },
  {
    name: "海天",
    name_en: "Haday",
    aliases: "海天味业,海天酱油,Haitian",
    weekend_off: false,
    category: "食品饮料",
    note: "社区登记生产与销售岗多为非双休。",
    weekend_votes: 5,
    no_weekend_votes: 14,
  },
  {
    name: "老干妈",
    name_en: "Lao Gan Ma",
    aliases: "陶华碧,老干妈辣椒酱,Laoganma",
    weekend_off: false,
    category: "食品饮料",
    note: "社区登记工厂排班常见单休。",
    weekend_votes: 3,
    no_weekend_votes: 10,
  },
  {
    name: "三只松鼠",
    name_en: "Three Squirrels",
    aliases: "ThreeSquirrels,松鼠",
    weekend_off: false,
    category: "食品饮料",
    note: "社区反馈电商节奏加班较多。",
    weekend_votes: 4,
    no_weekend_votes: 13,
  },
  {
    name: "良品铺子",
    name_en: "Bestore",
    aliases: "良品,Bestore",
    weekend_off: false,
    category: "食品饮料",
    note: "社区登记零售与电商岗并非稳定双休。",
    weekend_votes: 5,
    no_weekend_votes: 12,
  },
  {
    name: "青岛啤酒",
    name_en: "Tsingtao",
    aliases: "青啤,Tsingtao Beer,青岛啤酒股份",
    weekend_off: true,
    category: "食品饮料",
    note: "社区多记办公室双休，产线轮班另算。",
    weekend_votes: 12,
    no_weekend_votes: 5,
  },
  {
    name: "茅台",
    name_en: "Moutai",
    aliases: "贵州茅台,飞天茅台,Kweichow Moutai",
    weekend_off: true,
    category: "食品饮料",
    note: "社区多记机关与办公室为双休。",
    weekend_votes: 11,
    no_weekend_votes: 6,
  },
  {
    name: "宝洁",
    name_en: "P&G",
    aliases: "Procter & Gamble,P&G,海飞丝,舒肤佳,潘婷,飘柔,护舒宝",
    weekend_off: true,
    category: "日化洗护",
    note: "外企办公室社区普遍登记为双休。",
    weekend_votes: 18,
    no_weekend_votes: 2,
  },
  {
    name: "联合利华",
    name_en: "Unilever",
    aliases: "奥妙,中华牙膏,清扬,多芬,力士",
    weekend_off: true,
    category: "日化洗护",
    note: "社区多记办公室双休。",
    weekend_votes: 17,
    no_weekend_votes: 2,
  },
  {
    name: "立白",
    name_en: "Liby",
    aliases: "立白集团,Liby Group",
    weekend_off: false,
    category: "日化洗护",
    note: "社区登记销售与部分职能加班较多。",
    weekend_votes: 5,
    no_weekend_votes: 13,
  },
  {
    name: "蓝月亮",
    name_en: "Bluemoon",
    aliases: "蓝月亮洗衣液,Blue Moon",
    weekend_off: false,
    category: "日化洗护",
    note: "社区反馈并非全员稳定双休。",
    weekend_votes: 6,
    no_weekend_votes: 12,
  },
  {
    name: "高露洁",
    name_en: "Colgate",
    aliases: "Colgate-Palmolive,高露洁牙膏",
    weekend_off: true,
    category: "日化洗护",
    note: "外企办公室社区登记为双休。",
    weekend_votes: 13,
    no_weekend_votes: 2,
  },
  {
    name: "安踏",
    name_en: "Anta",
    aliases: "安踏体育,ANTA,斐乐,FILA",
    weekend_off: false,
    category: "服装运动",
    note: "社区反馈零售与总部节奏偏满。",
    weekend_votes: 6,
    no_weekend_votes: 16,
  },
  {
    name: "李宁",
    name_en: "Li-Ning",
    aliases: "LiNing,李宁运动",
    weekend_off: false,
    category: "服装运动",
    note: "社区登记为非双休，岗位差异大。",
    weekend_votes: 7,
    no_weekend_votes: 14,
  },
  {
    name: "特步",
    name_en: "Xtep",
    aliases: "特步国际,XTEP",
    weekend_off: false,
    category: "服装运动",
    note: "社区登记零售体系常见非双休。",
    weekend_votes: 4,
    no_weekend_votes: 11,
  },
  {
    name: "耐克",
    name_en: "Nike",
    aliases: "NIKE,耐克中国",
    weekend_off: true,
    category: "服装运动",
    note: "社区多记中国办公室为双休。",
    weekend_votes: 15,
    no_weekend_votes: 3,
  },
  {
    name: "阿迪达斯",
    name_en: "Adidas",
    aliases: "adidas,Adidas Originals,三叶草",
    weekend_off: true,
    category: "服装运动",
    note: "社区多记办公室双休。",
    weekend_votes: 14,
    no_weekend_votes: 3,
  },
  {
    name: "优衣库",
    name_en: "UNIQLO",
    aliases: "Uniqlo,迅销,UT",
    weekend_off: true,
    category: "服装运动",
    note: "办公室多为双休；门店按排班，不是标准双休。",
    weekend_votes: 12,
    no_weekend_votes: 8,
  },
  {
    name: "无印良品",
    name_en: "MUJI",
    aliases: "MUJI,良品,无印",
    weekend_off: true,
    category: "服装运动",
    note: "社区多记办公室双休，门店另算。",
    weekend_votes: 13,
    no_weekend_votes: 4,
  },
  {
    name: "波司登",
    name_en: "Bosideng",
    aliases: "波司登羽绒服",
    weekend_off: false,
    category: "服装运动",
    note: "社区登记为非双休。",
    weekend_votes: 4,
    no_weekend_votes: 10,
  },
  {
    name: "海澜之家",
    name_en: "HLA",
    aliases: "HLA,海澜",
    weekend_off: false,
    category: "服装运动",
    note: "社区登记零售体系多为排班制。",
    weekend_votes: 3,
    no_weekend_votes: 11,
  },
  {
    name: "华为",
    name_en: "Huawei",
    aliases: "HUAWEI,华为技术,Mate,Pura,鸿蒙",
    weekend_off: false,
    category: "数码家电",
    note: "社区普遍登记研发与多部门加班文化，非稳定双休。",
    weekend_votes: 3,
    no_weekend_votes: 28,
  },
  {
    name: "小米",
    name_en: "Xiaomi",
    aliases: "MI,Redmi,红米,Xiaomi",
    weekend_off: false,
    category: "数码家电",
    note: "社区反馈互联网硬件节奏，双休不稳定。",
    weekend_votes: 5,
    no_weekend_votes: 24,
  },
  {
    name: "荣耀",
    name_en: "Honor",
    aliases: "Honor,荣耀手机",
    weekend_off: false,
    category: "数码家电",
    note: "社区登记为非双休。",
    weekend_votes: 4,
    no_weekend_votes: 16,
  },
  {
    name: "OPPO",
    name_en: "OPPO",
    aliases: "oppo,欧珀,一加,OnePlus",
    weekend_off: false,
    category: "数码家电",
    note: "社区反馈研发节奏偏满。",
    weekend_votes: 5,
    no_weekend_votes: 18,
  },
  {
    name: "vivo",
    name_en: "vivo",
    aliases: "VIVO,维沃,iQOO",
    weekend_off: false,
    category: "数码家电",
    note: "社区登记为非双休。",
    weekend_votes: 5,
    no_weekend_votes: 17,
  },
  {
    name: "苹果",
    name_en: "Apple",
    aliases: "Apple Inc,iPhone,iPad,Mac,Apple Store",
    weekend_off: true,
    category: "数码家电",
    note: "中国办公室社区多记双休；零售店按排班。",
    weekend_votes: 16,
    no_weekend_votes: 5,
  },
  {
    name: "三星",
    name_en: "Samsung",
    aliases: "SAMSUNG,三星电子,Galaxy",
    weekend_off: true,
    category: "数码家电",
    note: "社区多记中国办公室双休。",
    weekend_votes: 13,
    no_weekend_votes: 4,
  },
  {
    name: "海尔",
    name_en: "Haier",
    aliases: "Haier,卡萨帝,Casarte",
    weekend_off: false,
    category: "数码家电",
    note: "社区登记制造与部分职能加班较多。",
    weekend_votes: 6,
    no_weekend_votes: 15,
  },
  {
    name: "美的",
    name_en: "Midea",
    aliases: "Midea,美的集团,小天鹅",
    weekend_off: false,
    category: "数码家电",
    note: "社区反馈产研节奏偏满，因事业部而异。",
    weekend_votes: 7,
    no_weekend_votes: 16,
  },
  {
    name: "格力",
    name_en: "Gree",
    aliases: "GREE,格力电器",
    weekend_off: false,
    category: "数码家电",
    note: "社区登记为非双休。",
    weekend_votes: 5,
    no_weekend_votes: 14,
  },
  {
    name: "欧莱雅",
    name_en: "L'Oréal",
    aliases: "Loreal,L'Oreal,巴黎欧莱雅,兰蔻,YSL,赫莲娜",
    weekend_off: true,
    category: "美妆个护",
    note: "外企办公室社区普遍登记双休。",
    weekend_votes: 16,
    no_weekend_votes: 3,
  },
  {
    name: "雅诗兰黛",
    name_en: "Estée Lauder",
    aliases: "Estee Lauder,ELC,MAC,倩碧,Clinique",
    weekend_off: true,
    category: "美妆个护",
    note: "社区多记办公室双休。",
    weekend_votes: 14,
    no_weekend_votes: 2,
  },
  {
    name: "完美日记",
    name_en: "Perfect Diary",
    aliases: "逸仙电商,PerfectDiary,小奥汀",
    weekend_off: false,
    category: "美妆个护",
    note: "社区反馈电商美妆节奏加班较多。",
    weekend_votes: 3,
    no_weekend_votes: 15,
  },
  {
    name: "花西子",
    name_en: "Florasis",
    aliases: "Florasis,花西子彩妆",
    weekend_off: false,
    category: "美妆个护",
    note: "社区登记为非双休。",
    weekend_votes: 3,
    no_weekend_votes: 12,
  },
  {
    name: "珀莱雅",
    name_en: "Proya",
    aliases: "Proya,珀莱雅化妆品",
    weekend_off: false,
    category: "美妆个护",
    note: "社区反馈并非稳定双休。",
    weekend_votes: 5,
    no_weekend_votes: 11,
  },
  {
    name: "星巴克",
    name_en: "Starbucks",
    aliases: "Starbucks Coffee,星巴克咖啡",
    weekend_off: true,
    category: "餐饮零售",
    note: "办公室多为双休；门店伙伴按排班。",
    weekend_votes: 13,
    no_weekend_votes: 9,
  },
  {
    name: "瑞幸",
    name_en: "Luckin",
    aliases: "Luckin Coffee,瑞幸咖啡",
    weekend_off: false,
    category: "餐饮零售",
    note: "社区反馈总部与门店都偏满，非稳定双休。",
    weekend_votes: 4,
    no_weekend_votes: 20,
  },
  {
    name: "蜜雪冰城",
    name_en: "Mixue",
    aliases: "Mixue,雪王,蜜雪",
    weekend_off: false,
    category: "餐饮零售",
    note: "社区登记总部与门店均常见非双休。",
    weekend_votes: 2,
    no_weekend_votes: 22,
  },
  {
    name: "喜茶",
    name_en: "HEYTEA",
    aliases: "Heytea,喜茶茶饮",
    weekend_off: false,
    category: "餐饮零售",
    note: "社区登记新茶饮节奏加班较多。",
    weekend_votes: 4,
    no_weekend_votes: 16,
  },
  {
    name: "奈雪的茶",
    name_en: "Nayuki",
    aliases: "奈雪,Nayuki",
    weekend_off: false,
    category: "餐饮零售",
    note: "社区登记为非双休。",
    weekend_votes: 4,
    no_weekend_votes: 14,
  },
  {
    name: "麦当劳",
    name_en: "McDonald's",
    aliases: "McDonalds,金拱门,McCafé,麦麦",
    weekend_off: true,
    category: "餐饮零售",
    note: "办公室社区多记双休；餐厅员工按排班。",
    weekend_votes: 12,
    no_weekend_votes: 8,
  },
  {
    name: "肯德基",
    name_en: "KFC",
    aliases: "Kentucky,百胜,Yum China,必胜客",
    weekend_off: true,
    category: "餐饮零售",
    note: "百胜中国办公室社区多记双休；门店排班另算。",
    weekend_votes: 11,
    no_weekend_votes: 8,
  },
  {
    name: "海底捞",
    name_en: "Haidilao",
    aliases: "Haidilao,海底捞火锅",
    weekend_off: false,
    category: "餐饮零售",
    note: "门店高强度排班；社区登记整体为非双休。",
    weekend_votes: 3,
    no_weekend_votes: 19,
  },
  {
    name: "宜家",
    name_en: "IKEA",
    aliases: "IKEA,宜家家居",
    weekend_off: true,
    category: "餐饮零售",
    note: "社区多记办公室双休，商场岗位按排班。",
    weekend_votes: 14,
    no_weekend_votes: 5,
  },
  {
    name: "比亚迪",
    name_en: "BYD",
    aliases: "BYD,比亚迪汽车,仰望,腾势",
    weekend_off: false,
    category: "汽车出行",
    note: "社区普遍登记制造与研发加班多，非稳定双休。",
    weekend_votes: 4,
    no_weekend_votes: 26,
  },
  {
    name: "特斯拉",
    name_en: "Tesla",
    aliases: "Tesla China,特斯拉中国,Model Y,Model 3",
    weekend_off: false,
    category: "汽车出行",
    note: "工厂与部分岗位社区登记加班密集。",
    weekend_votes: 5,
    no_weekend_votes: 18,
  },
  {
    name: "蔚来",
    name_en: "NIO",
    aliases: "NIO,蔚来汽车",
    weekend_off: false,
    category: "汽车出行",
    note: "社区反馈新造车节奏，双休不稳定。",
    weekend_votes: 6,
    no_weekend_votes: 17,
  },
  {
    name: "吉利",
    name_en: "Geely",
    aliases: "Geely,吉利汽车,极氪,ZEEKR,领克",
    weekend_off: false,
    category: "汽车出行",
    note: "社区登记为非双休，因品牌公司而异。",
    weekend_votes: 6,
    no_weekend_votes: 15,
  },
  {
    name: "同仁堂",
    name_en: "Tong Ren Tang",
    aliases: "北京同仁堂,Tongrentang",
    weekend_off: true,
    category: "医药健康",
    note: "社区多记门店与机关相对稳定双休。",
    weekend_votes: 12,
    no_weekend_votes: 5,
  },
  {
    name: "云南白药",
    name_en: "Yunnan Baiyao",
    aliases: "白药牙膏,YunnanBaiyao",
    weekend_off: true,
    category: "医药健康",
    note: "社区多记办公室双休。",
    weekend_votes: 11,
    no_weekend_votes: 4,
  },
  {
    name: "字节跳动",
    name_en: "ByteDance",
    aliases: "抖音,TikTok,今日头条,西瓜视频,Dongyin,ByteDance",
    weekend_off: false,
    category: "其他",
    note: "社区普遍登记大小周或加班文化，非稳定双休。",
    weekend_votes: 2,
    no_weekend_votes: 30,
  },
  {
    name: "拼多多",
    name_en: "PDD",
    aliases: "Pinduoduo,Temu,拼多多",
    weekend_off: false,
    category: "其他",
    note: "社区普遍登记高强度加班。",
    weekend_votes: 1,
    no_weekend_votes: 29,
  },
  {
    name: "美团",
    name_en: "Meituan",
    aliases: "美团外卖,美团优选,Keeta",
    weekend_off: false,
    category: "其他",
    note: "社区登记互联网岗位加班较多。",
    weekend_votes: 3,
    no_weekend_votes: 23,
  },
  {
    name: "京东",
    name_en: "JD",
    aliases: "京东商城,JD.com,京东物流",
    weekend_off: false,
    category: "其他",
    note: "社区反馈多次调整，整体仍常记为非双休。",
    weekend_votes: 7,
    no_weekend_votes: 20,
  },
  {
    name: "阿里巴巴",
    name_en: "Alibaba",
    aliases: "淘宝,天猫,闲鱼,支付宝,盒马,阿里",
    weekend_off: false,
    category: "其他",
    note: "社区登记因BU而异，整体仍常被记为非双休。",
    weekend_votes: 8,
    no_weekend_votes: 21,
  },
];

export async function ensureSeed(sql: Sql): Promise<void> {
  const rows = await sql<{ n: number }>`select count(*)::int as n from brands`;
  if ((rows[0]?.n ?? 0) === 0) {
    for (const b of SEED) {
      await sql`
        insert into brands (
          name, name_en, aliases, weekend_off, category, note,
          weekend_votes, no_weekend_votes
        ) values (
          ${b.name}, ${b.name_en}, ${b.aliases}, ${b.weekend_off}, ${b.category}, ${b.note},
          ${b.weekend_votes}, ${b.no_weekend_votes}
        )
        on conflict (name) do nothing
      `;
    }
  }

  const pepsi = SEED.find((b) => b.name === "百事");
  if (pepsi) {
    await sql`
      update brands
      set aliases = ${pepsi.aliases}, updated_at = now()
      where name = '百事' and aliases not like '%乐事%'
    `;
  }
}
