/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ShareRouteImport } from './routes/share'
import { Route as BrandsIndexRouteImport } from './routes/brands.index'
import { Route as BrandsIdRouteImport } from './routes/brands.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsIndexRoute = BrandsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrandsRoute,
} as any)
const BrandsIdRoute = BrandsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BrandsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brands': typeof BrandsRouteWithChildren
  '/register': typeof RegisterRoute
  '/share': typeof ShareRoute
  '/brands/$id': typeof BrandsIdRoute
  '/brands/': typeof BrandsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/register': typeof RegisterRoute
  '/share': typeof ShareRoute
  '/brands/$id': typeof BrandsIdRoute
  '/brands': typeof BrandsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brands': typeof BrandsRouteWithChildren
  '/register': typeof RegisterRoute
  '/share': typeof ShareRoute
  '/brands/$id': typeof BrandsIdRoute
  '/brands/': typeof BrandsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/brands'
    | '/register'
    | '/share'
    | '/brands/$id'
    | '/brands/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/register' | '/share' | '/brands/$id' | '/brands'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/brands'
    | '/register'
    | '/share'
    | '/brands/$id'
    | '/brands/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BrandsRoute: typeof BrandsRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ShareRoute: typeof ShareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/': {
      id: '/brands/'
      path: '/'
      fullPath: '/brands/'
      preLoaderRoute: typeof BrandsIndexRouteImport
      parentRoute: typeof BrandsRoute
    }
    '/brands/$id': {
      id: '/brands/$id'
      path: '/$id'
      fullPath: '/brands/$id'
      preLoaderRoute: typeof BrandsIdRouteImport
      parentRoute: typeof BrandsRoute
    }
  }
}

interface BrandsRouteChildren {
  BrandsIdRoute: typeof BrandsIdRoute
  BrandsIndexRoute: typeof BrandsIndexRoute
}

const BrandsRouteChildren: BrandsRouteChildren = {
  BrandsIdRoute: BrandsIdRoute,
  BrandsIndexRoute: BrandsIndexRoute,
}

const BrandsRouteWithChildren =
  BrandsRoute._addFileChildren(BrandsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BrandsRoute: BrandsRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ShareRoute: ShareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
